title: Pepu Popa
author: Feroake
email: your-email@domain.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Pepu and Popa were 2 entities that were meant to save the backrooms. Our R&D group decided to include them to keep other entites away from humans.
  Although it is widely accepted that humans do not enter the backrooms at all costs, we still are not sure about the possible ways to enter the backrooms. 
  So if an strangers steps foot into the backrooms, Pepu and Popa would guide the human using physical force. The AI team decided to use physical force instead
  of emotional because of time constraints (the site manager would threaten to fire us). 
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
